image: electronuserland/builder:wine

pipelines:
  branches:
    dev:
      - step:
          name: "Build and Upload"
          deployment: production
          caches:
            - node
          script:
            - npm i
            - npm run electron:build
          artifacts:
            - dist_electron/*.snap
            - dist_electron/*.AppImage