version: '3'

volumes:
  db_data:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: "M4tr1x123"
      ACCEPT_EULA: "Y"
    volumes:
      # Volume dos dados
      - db_data:/var/opt/mssql/
    ports:
      - 1433:1433
